name: JMeter Performance Tests

on:
  push:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Prepare folders
        run: |
          rm -rf results
          rm -rf reports/all_reports
          mkdir -p results
          mkdir -p reports/all_reports

      - name: Run Load Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/status_load_test.jmx \
            -l results/status_load.jtl \
            -e \
            -o reports/all_reports/status_load_report

      - name: Run Stress Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/status_stress_test.jmx \
            -l results/status_stress.jtl \
            -e \
            -o reports/all_reports/status_stress_report

      - name: Run Endurance Test
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/status_endurance_test.jmx \
            -l results/status_endurance.jtl \
            -e \
            -o reports/all_reports/status_endurance_report

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: reports/all_reports